# Generated by Django 5.0.3 on 2024-04-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=100)),
                ('email', models.TextField(max_length=100)),
                ('telefone', models.TextField(max_length=20)),
                ('nacionalidade', models.TextField(max_length=50)),
                ('data_nasc', models.TextField()),
                ('interesse', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='passeio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bairro', models.TextField(max_length=100)),
            ],
        ),
    ]
