# Generated by Django 5.0.3 on 2024-04-08 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=100)),
                ('email', models.TextField(max_length=100)),
                ('telefone', models.TextField(max_length=20)),
                ('nacionalidade', models.TextField(max_length=50)),
                ('data_nasc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='passeio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bairro', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id_post', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.TextField()),
                ('txt', models.TextField(max_length=100)),
                ('data_hora_post', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='street.cliente')),
                ('id_passeio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='street.passeio')),
            ],
        ),
    ]
