# Generated by Django 5.0.3 on 2024-04-03 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('street', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='passeio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bairro', models.TextField(max_length=100)),
                ('data_hora', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id_post', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.TextField()),
                ('txt', models.TextField(max_length=100)),
                ('data_hora_post', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='street.cliente')),
                ('id_passeio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='street.passeio')),
            ],
        ),
    ]
